name: Publish package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'tandem-dnd'
          workload_identity_provider: 'projects/691397588692/locations/global/workloadIdentityPools/github-workload-identity-pool/providers/github-workload-provider'
          service_account: 'tandem-github@tandem-dnd.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Publish package'
        run: npx google-artifactregistry-auth && npm publish