name: Publish package

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/681834564451/locations/global/workloadIdentityPools/github/providers/habitual-repos'
          service_account: 'tandem-github@habitual-410821.iam.gserviceaccount.com'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
      # - name: 'Install dependencies'
      #   run: npm ci
      - name: 'Publish package'
        run: npm run artifactregistry-login && npm publish